# Generated by Django 2.2.2 on 2019-06-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_dogs', '0001_initial'),
        ('petco_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pets',
            field=models.ManyToManyField(blank=True, to='create_dogs.CreatePet'),
        ),
    ]
